[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "frankenphp run --bind=0.0.0.0:80"
restartPolicyMaxRetries = 5
restartPolicyWindowSeconds = 60
healthcheckPath = "/health"
healthcheckTimeout = 10
